- hosts: master
  become: yes
  tasks:
    - name: install cilium CLI
      shell: |
        CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
        CLI_ARCH=amd64
        if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
        curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
        sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
        tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
        rm -rf cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
        chmod a+x /usr/local/bin/cilium
      args:
        creates: /usr/local/bin/cilium

    - name: install Pod network
      become: yes
      become_user: douball
      shell: cilium install --set bgpControlPlane.enabled=true,kubeProxyReplacement=true,externalIPs.enabled=true,nodePort.enabled=true,hostPort.enabled=true,k8s-require-ipv4-pod-cidr=true,gatewayAPI.enabled=true,hubble.relay.enabled=true,hubble.ui.enabled=true >> pod_network_setup.log
      args:
        chdir: $HOME
        creates: pod_network_setup.log